import { Providers } from './NextUiProvider'
import Navbar from './components/Navbar'
import Sidebar from './components/Sidebar'
import { GlobalContextProvider } from './context/GlobalContext'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalContextProvider>
        <body className={inter.className}>
          <Providers>
            <div className='wrapper flex flex-row overflow-x-hidden'>
              <div>
                <Sidebar />
              </div>
              <div className='w-full'>
                <Navbar />
                {children}
              </div>
            </div>
          </Providers>
        </body>
      </GlobalContextProvider>
    </html>
  )
}
