import Image from 'next/image'
import { Providers } from './NextUiProvider'
import { GlobalContextProvider } from './context/GlobalContext'
import './globals.css'
import { Inter } from 'next/font/google'
import bg from "../public/Pics/bg.png"
// import "@/app/styles.scss"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalContextProvider>
        <body className={inter.className}>
          <Providers>
            <div className=' flex flex-row overflow-x-hidden'>
              <Image src={bg}
                className="h-[100vh] w-[100vw] object-cover fixed inset-0 z-[-1] "
                alt=''
              />
              <div className='w-full'>
                {children}
              </div>
            </div>
          </Providers>
        </body>
      </GlobalContextProvider>
    </html>
  )
}
